config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount API::Base => '/api'
  root :to => 'charts#index'
  
  resources :charts, only: [:index, :new, :edit, :update, :create, :show, :destroy]
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Chart.it"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag :cocoon
    = favicon_link_tag 'piechart.png'
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
        %a.navbar-brand(href=charts_path)
          =append_icon("Chart.it", "pie-chart")
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav.pull-right
            -if user_signed_in?
              %li= link_to 'Sign out', destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: 'delete'
            -else
              %li= link_to 'Sign Up', new_user_registration_path

    .container
      - if msg = flash[:error]
        #flash.alert.alert-error= msg
      = content_for?(:body) ? content_for(:body) : yield


  .container.footer
    %footer
      %p &copy; Kyle Prifogle #{Date.today.year}

app/views/layouts/charts.html.haml
-content_for(:body) do
  .container
    .row
      .col-lg-12.main_area
        .col-lg-9.primary_area
          = yield
        .col-lg-3.sidebar_area
          .sidebar-nav
            %h3 Chart Navigator
            %ul.nav.nav-list
              %li.nav-header Select a chart
              -current_user.charts.each do |chart|
                %li
                  -if chart.persisted?
                    .inline
                      %h4
                        = link_to chart.safe_name, chart_path(chart)
                        = link_to append_icon("","pencil"), edit_chart_path(chart)
                        = link_to append_icon("","trash"), chart_path(chart), :method => :delete
              %li.new= link_to append_icon("New Chart","plus"), new_chart_path

= render template: 'layouts/application'